// Build plugin-internal prompt skills: src/prompts/*.md -> src/generated/prompts.ts.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(root, 'src/prompts')
const output = join(root, 'src/generated/prompts.ts')

const entries = readdirSync(source).filter(file => file.endsWith('.md')).sort()
  .map(file => [file.slice(0, -3), readFileSync(join(source, file), 'utf8')])
const body = entries.map(([name, content]) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`).join('\n')
mkdirSync(dirname(output), { recursive: true })
writeFileSync(output, `// Generated by scripts/build-skills.mjs from src/prompts/*.md; do not edit.\nexport const PROMPTS: Record<string, string> = {\n${body}\n}\n`)
console.log(`generated ${entries.length} prompt skills -> src/generated/prompts.ts`)
